language: node_js
node_js:
  - 12
  - 14
install:
  - npm install -g npm
  - npm install
script:
  - npm run lint
  - npm test
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: coverage
      node_js: lts/*
      script:
        - npm install -g coveralls
        - npm run test -- --coverage && cat ./coverage/lcov.info | coveralls
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
