
name: Release
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x

      - name: Install dependencies
        run: npm ci

      - name: Release
        run: npx semantic-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
